import { Product } from '../products'

export const allPurposeCleaners: Product[] = [
  {
    name: 'Mr. Clean',
    company: 'Procter & Gamble',
    percentCanadian: 0,
    notes: 'Made in the USA.',
    categoryId: 'allPurposeCleaners',
    aliases: ['mr clean all purpose cleaner'],
    popularity: 95,
  },
  {
    name: 'Lysol',
    company: 'Reckitt Benckiser',
    percentCanadian: 0,
    notes: 'Made in the USA.',
    categoryId: 'allPurposeCleaners',
    aliases: ['lysol all purpose cleaner'],
    popularity: 90,
  },
  {
    name: 'Pine-Sol',
    company: 'Clorox',
    percentCanadian: 0,
    notes: 'Made in the USA.',
    categoryId: 'allPurposeCleaners',
    aliases: ['pine sol all purpose cleaner'],
    popularity: 85,
  },
  {
    name: 'Compliments',
    company: 'Sobeys',
    percentCanadian: 100,
    notes: 'Sobeys store brand, made entirely in Canada.',
    categoryId: 'allPurposeCleaners',
    aliases: ['compliments all purpose cleaner'],
    popularity: 75,
  },
  {
    name: 'Dr. Bronners',
    company: 'Dr. Bronner’s Magic Soaps',
    percentCanadian: 0,
    notes: 'Made in the USA.',
    categoryId: 'allPurposeCleaners',
    aliases: ['dr bronners all purpose cleaner'],
    popularity: 70,
  },
  {
    name: 'President’s Choice',
    company: 'Loblaw Companies',
    percentCanadian: 100,
    notes: 'Loblaw’s private label cleaner.',
    categoryId: 'allPurposeCleaners',
    aliases: ['presidents choice all purpose cleaner', 'pc all purpose cleaner'],
    popularity: 80,
  },
  {
    name: 'Great Value',
    company: 'Walmart Canada',
    percentCanadian: 50,
    notes: 'Walmart’s store brand cleaner, widely available in Walmart locations across Canada.',
    categoryId: 'allPurposeCleaners',
    aliases: ['great value all purpose cleaner', 'walmart all purpose cleaner'],
    popularity: 75,
  },
  {
    name: 'Method',
    company: 'Method Products',
    percentCanadian: 0,
    notes: 'Made in the USA.',
    categoryId: 'allPurposeCleaners',
    aliases: ['method all purpose cleaner'],
    popularity: 65,
  },
  {
    name: 'Seventh Generation',
    company: 'Unilever',
    percentCanadian: 0,
    notes: 'Made in USA.',
    categoryId: 'allPurposeCleaners',
    aliases: ['seventh generation all purpose cleaner'],
    popularity: 60,
  },
  {
    name: 'Eco-Max',
    company: 'Eco Max',
    percentCanadian: 100,
    notes: 'Made entirely in Canada and available in stores across the country.',
    categoryId: 'allPurposeCleaners',
    aliases: ['eco-max all purpose cleaner'],
    popularity: 70,
  },
]

export const allPurposeCleanerCategory = {
  name: 'All Purpose Cleaners',
  description:
    'Cleaners that are suitable for a variety of surfaces including countertops, bathroom surfaces, floors, and more.',
  aliases: ['cleaning supplies', 'cleaners', 'multipurpose cleaners'],
}
