import { Product } from '../products'

export const chocolate: Product[] = [
  {
    name: 'Cadbury',
    company: 'Mondelēz International',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Originally a British brand, owned by an American confectionery, Mondelēz International.',
    categoryId: 'chocolate',
    aliases: ['cadbury chocolate'],
    popularity: 95,
  },
  {
    name: 'Hershey',
    company: 'The Hershey Company',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'American chocolate brand.',
    categoryId: 'chocolate',
    aliases: ['hershey chocolate'],
    popularity: 90,
  },
  {
    name: 'Ferrero Rocher',
    company: 'Ferrero SpA',
    countryCode: 'IT',
    percentCanadian: 0,
    notes: 'Italian manufacturer of branded chocolate.',
    categoryId: 'chocolate',
    aliases: ['ferrero rocher'],
    popularity: 85,
  },
  {
    name: 'Kit Kat',
    company: 'Nestle Canada',
    countryCode: 'CA',
    percentCanadian: 0,
    notes: 'Produced globally each year by Nestle, which acquired Rowntrees in 1988. Owned by Swiss multinational Nestle.',
    categoryId: 'chocolate',
    aliases: ['kit kat chocolate'],
    popularity: 80,
  },
  {
    name: 'Smarties',
    company: 'Nestle Canada',
    countryCode: 'CA',
    percentCanadian: 0,
    notes: 'Another Nestle product, different candy-coated chocolate than the American smarties. Owned by Swiss multinational Nestle.',
    categoryId: 'chocolate',
    aliases: ['smarties candy'],
    popularity: 75,
  },
  {
    name: 'Aero',
    company: 'Nestle Canada',
    countryCode: 'CA',
    percentCanadian: 0,
    notes: 'A UK-based chocolate product that found its way to Canada. Owned by Swiss multinational Nestle.',
    categoryId: 'chocolate',
    aliases: ['aero chocolate'],
    popularity: 70,
  },
  {
    name: 'Ganong',
    company: 'Ganong Bros. Limited',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'Based in New Brunswick, Ganong Chocolates is Canada’s oldest chocolate and candy company.',
    categoryId: 'chocolate',
    aliases: ['ganong chocolate'],
    popularity: 65,
  },
  {
    name: 'Pot of Gold',
    company: 'Hershey Canada',
    countryCode: 'CA',
    percentCanadian: 30,
    notes: 'Canada’s first box-chocolate brand, now owned by Hershey, a US company.',
    categoryId: 'chocolate',
    aliases: ['pot of gold chocolate'],
    popularity: 60,
  },
  {
    name: 'Caramilk',
    company: 'Cadbury',
    countryCode: 'CA',
    percentCanadian: 50,
    notes: 'Invented in 1968 at Cadbury’s factory in the Eglinton and Sloane area of Toronto, still produced exclusively in Ontario. Cadbury is now owned by Mondelēz International.',
    categoryId: 'chocolate',
    aliases: ['caramilk chocolate'],
    popularity: 55,
  },
  {
    name: 'Coffee Crisp',
    company: 'Nestle Canada',
    countryCode: 'CA',
    percentCanadian: 50,
    notes: 'Developed based on a chocolate made in Canada since 1930s. Owned by Swiss multinational Nestle.',
    categoryId: 'chocolate',
    aliases: ['coffee crisp chocolate'],
    popularity: 50,
  },
]

export const chocolateCategory = {
  name: 'Chocolate',
  description:
    'A range of foods derived from cocoa (cacao), mixed with fat and finely powdered sugar to produce chocolate.',
  aliases: ['candy', 'cocoa', 'choc'],
}
