import { Product } from '../products'

export const energyDrinks: Product[] = [
  {
    name: 'Red Bull',
    company: 'Red Bull GmbH',
    countryCode: 'AT',
    percentCanadian: 0,
    notes: 'A well-known energy drink brand originated in Austria.',
    categoryId: 'energyDrinks',
    aliases: ['red bull energy drink'],
    popularity: 95,
  },
  {
    name: 'Monster Energy',
    company: 'Monster Beverage',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'An American energy drink brand widely available in Canada.',
    categoryId: 'energyDrinks',
    aliases: ['monster energy drink'],
    popularity: 90,
  },
  {
    name: 'Rockstar',
    company: 'Rockstar Inc.',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'American energy drink brand, popular and available in many Canadian stores.',
    categoryId: 'energyDrinks',
    aliases: ['rockstar energy drink'],
    popularity: 85,
  },
  {
    name: 'AMP Energy',
    company: 'PepsiCo',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Produced by PepsiCo, widely distributed across Canada.',
    categoryId: 'energyDrinks',
    aliases: ['amp energy drink'],
    popularity: 80,
  },
  {
    name: 'Full Throttle',
    company: 'The Coca-Cola Company',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Owned by the Coca-Cola Company and distributed across Canada.',
    categoryId: 'energyDrinks',
    aliases: ['full throttle energy drink'],
    popularity: 75,
  },
  {
    name: 'NOS Energy Drink',
    company: 'The Coca-Cola Company',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Produced by the Coca-Cola Company, widespread in Canadian stores.',
    categoryId: 'energyDrinks',
    aliases: ['nos energy drink'],
    popularity: 70,
  },
  {
    name: 'Relentless',
    company: 'The Coca-Cola Company',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Another energy drink brand under the Coca-Cola Company banner.',
    categoryId: 'energyDrinks',
    aliases: ['relentless energy drink'],
    popularity: 65,
  },
  {
    name: 'Mountain Dew Kickstart',
    company: 'PepsiCo',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'A PepsiCo product with a considerably high popularity in Canada.',
    categoryId: 'energyDrinks',
    aliases: ['mountain dew kickstart energy drink'],
    popularity: 60,
  },
  {
    name: 'Burn',
    company: 'The Coca-Cola Company',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Owned by the Coca-Cola Company and widely available across Canada.',
    categoryId: 'energyDrinks',
    aliases: ['burn energy drink'],
    popularity: 55,
  },
  {
    name: '5-hour Energy',
    company: 'Living Essentials',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'American brand energy shot that has a steady following in Canada.',
    categoryId: 'energyDrinks',
    aliases: ['5-hour energy drink'],
    popularity: 50,
  },
]

export const energyDrinksCategory = {
  name: 'Energy Drinks',
  description: 'Caffeinated beverages designed to boost energy levels, available in a variety of flavors and brands.',
  aliases: ['caffeinated drinks', 'energy boosters', 'sport drinks'],
}
