import { Product } from '../products'

export const frozenVegetables: Product[] = [
  {
    name: 'Compliments',
    company: 'Sobeys',
    percentCanadian: 100,
    notes: 'Compliments is a private label owned by Sobeys offering a variety of quality frozen vegetables.',
    categoryId: 'frozenVegetables',
    aliases: ['compliments vegetables'],
    popularity: 90,
  },
  {
    name: 'Green Giant',
    company: 'General Mills Canada',
    percentCanadian: 0,
    notes: 'American origin brand under General Mills. Stocks a variety of frozen vegetable products.',
    categoryId: 'frozenVegetables',
    aliases: ['green giant vegetables'],
    popularity: 85,
  },
  {
    name: 'Great Value',
    company: 'Walmart Canada',
    percentCanadian: 50,
    notes: 'Walmart’s in-house line of frozen vegetables, available in Walmart stores across Canada.',
    categoryId: 'frozenVegetables',
    aliases: ['great value vegetables'],
    popularity: 80,
  },
  {
    name: 'President’s Choice',
    company: 'Loblaw Companies',
    percentCanadian: 90,
    notes: 'Loblaw’s in-house brand of frozen vegetables. Widely available in Loblaw stores nationwide.',
    categoryId: 'frozenVegetables',
    aliases: ['president’s choice vegetables', 'pc vegetables'],
    popularity: 85,
  },
  {
    name: 'Europe’s Best',
    company: 'Hain Celestial Canada',
    percentCanadian: 25,
    notes:
      'European inspired frozen fruits and vegetables stocked in several grocery stores across Canada. Purely made in the US.',
    categoryId: 'frozenVegetables',
    aliases: ['europe’s best vegetables'],
    popularity: 70,
  },
  {
    name: 'Our Compliments',
    company: 'Sobey’s',
    percentCanadian: 100,
    notes: 'Sobey’s private label frozen vegetables available across their store chains.',
    categoryId: 'frozenVegetables',
    aliases: ['our compliments vegetables'],
    popularity: 75,
  },
  {
    name: 'No Name',
    company: 'Loblaw Companies',
    percentCanadian: 100,
    notes: 'No Name is Loblaw’s value-oriented line of generic brand grocery and household products.',
    categoryId: 'frozenVegetables',
    aliases: ['no name vegetables'],
    popularity: 80,
  },
  {
    name: 'Arctic Gardens',
    company: 'Bonduelle Canada',
    percentCanadian: 100,
    notes: 'A well-known Canadian brand with a large selection of frozen vegetables.',
    categoryId: 'frozenVegetables',
    aliases: ['arctic gardens vegetables'],
    popularity: 70,
  },
  {
    name: 'Irresistibles',
    company: 'Metro Inc.',
    percentCanadian: 100,
    notes: 'Irresistibles is a private label owned by Metro offering a variety of quality frozen vegetables.',
    categoryId: 'frozenVegetables',
    aliases: ['irresistibles vegetables'],
    popularity: 65,
  },
  {
    name: 'Watkins',
    company: 'Watkins Incorporated',
    percentCanadian: 0,
    categoryId: 'frozenVegetables',
    aliases: ['watkins vegetables'],
    notes: '',
    popularity: 60,
  },
]

export const frozenVegetablesCategory = {
  name: 'Frozen Vegetables',
  description: 'A variety of vegetables that have been blanched and then frozen, available in numerous combinations.',
  aliases: ['frozen produce', 'vegetables', 'frozen veggies'],
}
