import { Product } from '../products'

export const jewelryCleaners: Product[] = [
  {
    name: 'Connoisseurs',
    company: 'Connoisseurs Products Corporation',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['connoisseurs jewelry cleaner'],
    popularity: 90,
  },
  {
    name: 'Weiman',
    company: 'Weiman Products, LLC',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['weiman jewelry cleaner'],
    popularity: 80,
  },
  {
    name: 'Hagerty',
    company: 'W. J. Hagerty & Sons, Ltd., Inc.',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['hagerty jewelry cleaner'],
    popularity: 70,
  },
  {
    name: 'Brilliant',
    company: 'See All Industries, Inc.',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['brilliant jewelry cleaner'],
    popularity: 60,
  },
  {
    name: 'Blitz',
    company: 'Blitz Manufacturing Co., Inc.',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['blitz jewelry cleaner'],
    popularity: 55,
  },
  {
    name: 'Sparkle Bright',
    company: 'Kona Bay Inc.',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['sparkle bright jewelry cleaner'],
    popularity: 50,
  },
  {
    name: 'Powell Leonard',
    company: 'Powell Leonard Enterprises LLC.',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['powell leonard jewelry cleaner'],
    popularity: 45,
  },
  {
    name: 'Regent Labs',
    company: 'Regent Labs Inc.',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['regent labs jewelry cleaner'],
    popularity: 40,
  },
  {
    name: 'GODDARDS',
    company: 'Northern Labs, Inc.',
    percentCanadian: 0,
    notes: 'Purely manufactured in the US',
    categoryId: 'jewelryCleaners',
    aliases: ['goddards jewelry cleaner'],
    popularity: 30,
  },
]

export const jewelryCleanersCategory = {
  name: 'Jewelry Cleaners',
  description: 'Solutions used to clean, shine and protect jewelries.',
  aliases: ['cleaners2', 'shine.component', 'protect.component'],
}
