import { Product } from '../products'

export const laundryDetergent: Product[] = [
  {
    name: 'Tide',
    company: 'Procter & Gamble',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Manufactured by an American company.',
    categoryId: 'laundryDetergent',
    aliases: ['tide detergent'],
    popularity: 95,
  },
  {
    name: 'Sunlight',
    company: 'Unilever',
    countryCode: 'NL',
    percentCanadian: 50,
    notes: 'First introduced to the Canadian market, now globally available.',
    categoryId: 'laundryDetergent',
    aliases: ['sunlight detergent'],
    popularity: 90,
  },
  {
    name: 'Gain',
    company: 'Procter & Gamble',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'Manufactured by an American company.',
    categoryId: 'laundryDetergent',
    aliases: ['gain detergent'],
    popularity: 85,
  },
  {
    name: 'Persil',
    company: 'Henkel',
    countryCode: 'DE',
    percentCanadian: 0,
    notes: 'Manufactured by a German company, also available in Canadian stores.',
    categoryId: 'laundryDetergent',
    aliases: ['persil detergent'],
    popularity: 80,
  },
  {
    name: 'Purex',
    company: 'Henkel',
    countryCode: 'DE',
    percentCanadian: 0,
    notes: 'Partnered locally with Sun Products before their merger with Henkel.',
    categoryId: 'laundryDetergent',
    aliases: ['purex detergent'],
    popularity: 75,
  },
  {
    name: 'Arm & Hammer',
    company: 'Church & Dwight',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'American manufacturing company also available in Canada.',
    categoryId: 'laundryDetergent',
    aliases: ['arm and hammer detergent'],
    popularity: 70,
  },
  {
    name: 'Ivory Snow',
    company: 'Procter & Gamble',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'American manufactured product, also available in Canadian outlets.',
    categoryId: 'laundryDetergent',
    aliases: ['ivory snow detergent'],
    popularity: 65,
  },
  {
    name: 'President’s Choice Laundry Detergent',
    company: 'Loblaw Companies',
    countryCode: 'CA',
    percentCanadian: 90,
    notes: 'A Canadian private label product.',
    categoryId: 'laundryDetergent',
    aliases: ['pc laundry detergent', "president's choice laundry detergent"],
    popularity: 60,
  },
  {
    name: 'Compliments Laundry Detergent',
    company: 'Sobeys',
    countryCode: 'CA',
    percentCanadian: 90,
    notes: 'Sobeys’ private label detergent.',
    categoryId: 'laundryDetergent',
    aliases: ['compliments laundry detergent'],
    popularity: 55,
  },
  {
    name: 'Great Value Laundry Detergent',
    company: 'Walmart Canada',
    countryCode: 'CA',
    percentCanadian: 50,
    notes: 'Walmarts store brand detergent, widely available in Walmart locations across Canada.',
    categoryId: 'laundryDetergent',
    aliases: ['great value detergent', 'walmart detergent'],
    popularity: 50,
  },
]

export const detergentCategory = {
  name: 'Laundry detergent',
  description:
    'Substance used to clean clothing and fabrics, available in liquid, powder, or single-dose pack formats.',
  aliases: ['laundry soap', 'washing powder', 'laundry pods'],
}
