import { Product } from '../products'

export const mayonnaise: Product[] = [
  {
    name: 'Hellmann’s',
    company: 'Unilever',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'US brand, available throughout Canadian grocery stores.',
    categoryId: 'mayonnaise',
    aliases: ['hellmann’s mayo'],
    popularity: 95,
  },
  {
    name: 'Kraft',
    company: 'Kraft Heinz',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'US brand, widely available in Canadian grocery stores.',
    categoryId: 'mayonnaise',
    aliases: ['kraft mayo'],
    popularity: 90,
  },
  {
    name: 'Compliments',
    company: 'Sobeys',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'Canadian brand, sold at Sobeys, Foodland, and FreshCo.',
    categoryId: 'mayonnaise',
    aliases: ['compliments mayo'],
    popularity: 85,
  },
  {
    name: 'President’s Choice',
    company: 'Loblaws',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'Loblaws private label mayo, available in their stores countrywide.',
    categoryId: 'mayonnaise',
    aliases: ['pc mayo', "president's choice mayo"],
    popularity: 83,
  },
  {
    name: 'Great Value',
    company: 'Walmart Canada',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'Sold in Walmart stores across Canada.',
    categoryId: 'mayonnaise',
    aliases: ['great value mayo', 'walmart mayo'],
    popularity: 80,
  },
  {
    name: 'Kirkland Signature',
    company: 'Costco',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'US brand, available at all Costco locations',
    categoryId: 'mayonnaise',
    aliases: ['kirkland mayo', 'costco mayo'],
    popularity: 78,
  },
  {
    name: 'Neilson’s',
    company: 'Saputo',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'Canadian brand, available primarily in Ontario.',
    categoryId: 'mayonnaise',
    aliases: ['neilson’s mayo'],
    popularity: 70,
  },
  {
    name: 'Spectrum',
    company: 'Hain Celestial Canada',
    countryCode: 'US',
    percentCanadian: 50,
    notes: 'US based company but with Canadian Manufacturing.',
    categoryId: 'mayonnaise',
    aliases: ['spectrum mayo'],
    popularity: 65,
  },
  {
    name: 'Vegenaise',
    company: 'Follow Your Heart',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'US brand, available in many Canadian grocery stores.',
    categoryId: 'mayonnaise',
    aliases: ['vegan mayo', 'plant-based mayo'],
    popularity: 62,
  },
  {
    name: 'Chosen Foods',
    company: 'Chosen Foods',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'US brand, available in select Canadian grocery stores.',
    categoryId: 'mayonnaise',
    aliases: ['chosen foods mayo'],
    popularity: 60,
  },
]

export const mayoCategory = {
  name: 'Mayonnaise',
  description:
    'A stable emulsion of oil, egg yolk, and acid, usually vinegar or lemon. Commonly used as a spread or base for other sauces.',
  aliases: ['sauce', 'condiments', 'spread'],
}
