import { Product } from '../products'

export const shampoo: Product[] = [
  {
    name: 'TRESemme',
    company: 'Unilever',
    percentCanadian: 0,
    notes: 'Originating from the US. Available in most grocery stores across Canada.',
    categoryId: 'shampoo',
    aliases: ['tresemme shampoo'],
    popularity: 90,
  },
  {
    name: 'Pantene',
    company: 'Procter & Gamble',
    percentCanadian: 0,
    notes: 'A leading shampoo brand from the US. Sold widely across Canada.',
    categoryId: 'shampoo',
    aliases: ['pantene shampoo'],
    popularity: 95,
  },
  {
    name: 'Garnier Fructis',
    company: 'LOreal',
    percentCanadian: 0,
    notes: 'Originally a French brand. Available in most grocery stores across Canada.',
    categoryId: 'shampoo',
    aliases: ['garnier fructis shampoo', 'fructis shampoo'],
    popularity: 85,
  },
  {
    name: 'Dove',
    company: 'Unilever',
    percentCanadian: 0,
    notes: 'A well-known brand from the UK. Found mostly in major grocery stores nationwide.',
    categoryId: 'shampoo',
    aliases: ['dove shampoo'],
    popularity: 88,
  },
  {
    name: 'Head & Shoulders',
    company: 'Procter & Gamble',
    percentCanadian: 0,
    notes: 'Prominent US brand, widely available in Canada.',
    categoryId: 'shampoo',
    aliases: ['head and shoulders shampoo', 'head n shoulders shampoo'],
    popularity: 92,
  },
  {
    name: 'Herbal Essences',
    company: 'Procter & Gamble',
    percentCanadian: 0,
    notes: 'Another popular US brand. Available in most grocery stores across Canada.',
    categoryId: 'shampoo',
    aliases: ['herbal essences shampoo'],
    popularity: 80,
  },
  {
    name: 'OGX',
    company: 'Johnson & Johnson',
    percentCanadian: 0,
    notes: 'American brand with a wide range of products. Available in major stores in Canada.',
    categoryId: 'shampoo',
    aliases: ['ogx shampoo'],
    popularity: 78,
  },
  {
    name: 'L’Oreal',
    company: 'LOreal',
    percentCanadian: 0,
    notes: 'French multinational company. Its shampoos are widely available in Canada.',
    categoryId: 'shampoo',
    aliases: ['loreal shampoo', "l'oreal shampoo"],
    popularity: 90,
  },
  {
    name: 'John Frieda',
    company: 'Kao Corporation',
    percentCanadian: 0,
    notes:
      'British brand distributed by Japanese company, Kao Corporation. Found in most grocery stores across Canada.',
    categoryId: 'shampoo',
    aliases: ['john frieda shampoo'],
    popularity: 75,
  },
  {
    name: 'Aveeno',
    company: 'Johnson & Johnson',
    percentCanadian: 0,
    notes: 'An American brand known for using natural ingredients. Widely available in Canada.',
    categoryId: 'shampoo',
    aliases: ['aveeno shampoo'],
    popularity: 85,
  },
]

export const shampooCategory = {
  name: 'Shampoo',
  description: 'A hair care product, typically in liquid form, to clean and condition hair.',
  aliases: ['hair care', 'cleanser', 'conditioner'],
}
