import { Product } from '../products'

export const soda: Product[] = [
  {
    name: 'Coca-Cola',
    company: 'The Coca-Cola Company',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'An American brand, Coca-Cola products sold in Canada are produced locally but the company is U.S.-owned.',
    categoryId: 'soda',
    aliases: ['coke', 'coca cola'],
  },
  {
    name: 'Pepsi',
    company: 'PepsiCo',
    countryCode: 'US',
    percentCanadian: 0,
    notes: 'An American brand, Pepsi products sold in Canada are produced locally but the company is U.S.-owned.',
    categoryId: 'soda',
    aliases: ['pepsi'],
  },
  {
    name: 'Canada Dry',
    company: 'Keurig Dr Pepper',
    countryCode: 'US',
    percentCanadian: 50,
    notes:
      'Originally a Canadian brand, now owned by the American company Keurig Dr Pepper. Some production still occurs in Canada.',
    categoryId: 'soda',
    aliases: ['canada dry'],
  },
  {
    name: 'Crush',
    company: 'Keurig Dr Pepper',
    countryCode: 'US',
    percentCanadian: 50,
    notes: 'An American brand, but popular in Canada with some local production.',
    categoryId: 'soda',
    aliases: ['crush'],
  },
  {
    name: 'Big 8',
    company: 'Big 8 Beverages',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'A Canadian brand based in Nova Scotia, offering a variety of soft drinks.',
    categoryId: 'soda',
    aliases: ['big 8'],
  },
  {
    name: 'Bec Cola',
    company: 'Bec Soda Inc.',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'A Quebec-based company producing organic cola sweetened with maple syrup.',
    categoryId: 'soda',
    aliases: ['bec cola'],
  },
  {
    name: 'Brio Chinotto',
    company: 'Brio Beverages Inc.',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'A Canadian-produced Italian-style soda popular in Italian communities.',
    categoryId: 'soda',
    aliases: ['brio', 'chinotto'],
  },
  {
    name: "Bull's Head",
    company: "Bull's Head",
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'A Quebec-based brand best known for its ginger ale.',
    categoryId: 'soda',
    aliases: ["bull's head"],
  },
  {
    name: 'Schweppes',
    company: 'Keurig Dr Pepper',
    countryCode: 'US',
    percentCanadian: 50,
    notes: 'Originally a Swiss brand, now owned by Keurig Dr Pepper. Some production occurs in Canada.',
    categoryId: 'soda',
    aliases: ['schweppes'],
  },
  {
    name: '7UP',
    company: 'Keurig Dr Pepper',
    countryCode: 'US',
    percentCanadian: 50,
    notes: 'An American brand, but popular in Canada with some local production.',
    categoryId: 'soda',
    aliases: ['7up', 'seven up'],
  },
]
