import { Product } from '../products'

export const sparklingWater: Product[] = [
  {
    name: 'Perrier',
    company: 'Nestlé France',
    percentCanadian: 0,
    notes: 'French brand of natural bottled mineral water, wholly owned by Nestlé.',
    categoryId: 'sparklingWater',
    aliases: ['perrier water'],
    popularity: 90,
  },
  {
    name: 'Bubly',
    company: 'PepsiCo',
    percentCanadian: 0,
    notes: 'American brand of sparkling water owned by PepsiCo.',
    categoryId: 'sparklingWater',
    aliases: ['bubly water'],
    popularity: 85,
  },
  {
    name: 'LaCroix',
    company: 'National Beverage',
    percentCanadian: 0,
    notes: 'American brand of carbonated water owned by National Beverage.',
    categoryId: 'sparklingWater',
    aliases: ['lacroix water'],
    popularity: 70,
  },
  {
    name: 'San Pellegrino',
    company: 'Nestlé Italy',
    percentCanadian: 0,
    notes: 'Italian brand of mineral water and assorted real-fruit beverages, owned by Nestlé.',
    categoryId: 'sparklingWater',
    aliases: ['san pellegrino water'],
    popularity: 65,
  },
  {
    name: 'Dasani',
    company: 'Coca-Cola Company',
    percentCanadian: 0,
    notes: 'American brand of bottled water and sparkling water, owned by the Coca-Cola Company.',
    categoryId: 'sparklingWater',
    aliases: ['dasani water'],
    popularity: 60,
  },
  {
    name: 'Nestle Pure Life',
    company: 'Nestlé Waters North America',
    percentCanadian: 0,
    notes: 'American brand of bottled and sparkling water, owned by Nestlé Waters North America.',
    categoryId: 'sparklingWater',
    aliases: ['nestle pure life water'],
    popularity: 55,
  },
  {
    name: 'Evian',
    company: 'Danone',
    percentCanadian: 0,
    notes: 'French brand of mineral water owned by Danone.',
    categoryId: 'sparklingWater',
    aliases: ['evian water'],
    popularity: 50,
  },
  {
    name: 'Schweppes',
    company: 'Keurig Dr Pepper/ The Coca-Cola Company',
    percentCanadian: 0,
    notes:
      'Swiss brand of beverage products owned by Keurig Dr Pepper for the US and The Coca-Cola Company for international markets.',
    categoryId: 'sparklingWater',
    aliases: ['schweppes water'],
    popularity: 80,
  },
  {
    name: 'Canada Dry',
    company: 'Keurig Dr Pepper',
    percentCanadian: 0,
    notes: 'American brand of soft drinks owned by Keurig Dr Pepper which also produces a brand of sparkling water.',
    categoryId: 'sparklingWater',
    aliases: ['canada dry water'],
    popularity: 90,
  },
  {
    name: 'Smartwater',
    company: 'Coca-Cola Company',
    percentCanadian: 0,
    notes: 'American brand of bottled water and sparkling water, owned by the Coca-Cola Company.',
    categoryId: 'sparklingWater',
    aliases: ['smartwater'],
    popularity: 45,
  },
  {
    name: 'Montellier',
    company: 'Nestlé Canada (Previously Independent)',
    countryCode: 'CA',
    percentCanadian: 70,
    notes:
      'Montellier is a Canadian sparkling water brand sourced from Quebec. Owned by Nestlé Canada, but still produced domestically.',
    categoryId: 'sparklingWater',
    aliases: ['montellier water', 'montellier sparkling water'],
    popularity: 80,
  },
  {
    name: 'Clearly Canadian',
    company: 'The Clearly Food & Beverage Company Ltd.',
    countryCode: 'CA',
    percentCanadian: 100,
    notes: 'Clearly Canadian is a proudly Canadian brand producing sparkling water sourced from Canadian springs.',
    categoryId: 'sparklingWater',
    aliases: ['clearly canadian', 'clearly canadian sparkling water'],
    popularity: 85,
  },
  {
    name: 'PC Sparkling Water',
    company: 'Loblaw Companies Ltd.',
    countryCode: 'CA',
    percentCanadian: 90,
    notes:
      'President’s Choice Sparkling Water is made for Loblaw, a fully Canadian company, but some ingredients (flavors) may be imported.',
    categoryId: 'sparklingWater',
    aliases: ['pc sparkling water', 'presidents choice sparkling water'],
    popularity: 80,
  },
]

export const sparklingWaterCategory = {
  name: 'Sparkling Water',
  description:
    'A type of water that has had carbon dioxide added to create carbonation. It is often flavored and used as a mixer for cocktails or enjoyed on its own.',
  aliases: ['carbonated water', 'soda water', 'seltzer'],
}
