import { Product } from '../products'

export const streamingServices: Product[] = [
  {
    name: 'CBC Gem',
    company: 'CBC',
    percentCanadian: 100,
    notes: 'Canadian based streaming service, available in Canada.',
    categoryId: 'streamingServices',
    aliases: ['cbc gem'],
    popularity: 95,
  },
  {
    name: 'Netflix',
    company: 'Netflix Inc.',
    percentCanadian: 0,
    notes: 'US originated streaming service, widely available in Canada.',
    categoryId: 'streamingServices',
    aliases: ['netflix canada'],
    popularity: 95,
  },
  {
    name: 'Crave',
    company: 'Bell Media',
    percentCanadian: 100,
    notes: 'A wholly Canadian streaming service. Offers Canadian as well as international content.',
    categoryId: 'streamingServices',
    aliases: ['crave tv', 'crave+'],
    popularity: 90,
  },
  {
    name: 'Disney+',
    company: 'Walt Disney Company',
    percentCanadian: 0,
    notes: 'US based streaming service, available in Canada.',
    categoryId: 'streamingServices',
    aliases: ['disney plus', 'disney'],
    popularity: 85,
  },
  {
    name: 'Amazon Prime Video',
    company: 'Amazon',
    percentCanadian: 0,
    notes: 'US based streaming service, available throughout Canada.',
    categoryId: 'streamingServices',
    aliases: ['prime video', 'amazon video'],
    popularity: 80,
  },
  {
    name: 'Apple TV+',
    company: 'Apple Inc.',
    percentCanadian: 0,
    notes: 'US originated streaming service, available in Canada.',
    categoryId: 'streamingServices',
    aliases: ['apple tv plus', 'apple tv'],
    popularity: 75,
  },
  {
    name: 'CBS All Access',
    company: 'ViacomCBS',
    percentCanadian: 0,
    notes: 'American streaming service, provided in Canada.',
    categoryId: 'streamingServices',
    aliases: ['cbs canada', 'cbs streaming'],
    popularity: 70,
  },
  {
    name: 'TSN Direct',
    company: 'Bell Media',
    percentCanadian: 100,
    notes: 'Streaming service focused on sports. Entirely Canadian.',
    categoryId: 'streamingServices',
    aliases: ['tsn streaming'],
    popularity: 65,
  },
  {
    name: 'Sportsnet Now',
    company: 'Rogers Media',
    percentCanadian: 100,
    notes: 'A 100% Canadian streaming service specifically for sports.',
    categoryId: 'streamingServices',
    aliases: ['sportsnet'],
    popularity: 60,
  },
  {
    name: 'CTV Direct',
    company: 'Bell Media',
    percentCanadian: 100,
    notes: 'Entirely Canadian, provides content from CTV network.',
    categoryId: 'streamingServices',
    aliases: ['ctv online'],
    popularity: 55,
  },
  {
    name: 'Global TV',
    company: 'Corus Entertainment',
    percentCanadian: 100,
    notes: '100% Canadian, streams content from the Global Television Network.',
    categoryId: 'streamingServices',
    aliases: ['global tv online'],
    popularity: 50,
  },
]

export const streamingServicesCategory = {
  name: 'Streaming Services',
  description: 'Digital platforms that provide on-demand entertainment content via the internet.',
  aliases: ['video streaming', 'tv streaming', 'online tv'],
}
