import { Product } from '../products'

export const whiskey: Product[] = [
  {
    name: 'Crown Royal',
    company: 'Diageo',
    percentCanadian: 100,
    notes: 'Top selling Canadian whisky in the United States. Manufactured entirely in Canada.',
    categoryId: 'whiskey',
    aliases: ['crown royal whiskey'],
    popularity: 90,
  },
  {
    name: 'Canadian Club',
    company: 'Beam Suntory',
    percentCanadian: 100,
    notes: 'A well-known Canadian rye whisky brand, originated from Windsor, Ontario. Distilled in Canada.',
    categoryId: 'whiskey',
    aliases: ['canadian club whiskey'],
    popularity: 85,
  },
  {
    name: 'Forty Creek',
    company: 'Campari Group',
    percentCanadian: 100,
    notes: 'An award-winning Canadian whisky brand made by Kittling Ridge Estate Wines & Spirits in Grimsby, Ontario.',
    categoryId: 'whiskey',
    aliases: ['forty creek whiskey'],
    popularity: 75,
  },
  {
    name: 'J.P. Wiser',
    company: 'Corby Spirit and Wine',
    percentCanadian: 100,
    notes: 'Produced in Ontario, It is Canada oldest continuously produced Canadian whisky.',
    categoryId: 'whiskey',
    aliases: ['j.p. wiser whiskey'],
    popularity: 80,
  },
  {
    name: 'Lot No. 40',
    company: 'Corby Spirit and Wine',
    percentCanadian: 100,
    notes: 'A premium Canadian rye whisky, all ingredients are sourced from Canada.',
    categoryId: 'whiskey',
    aliases: ['lot no. 40 whiskey'],
    popularity: 70,
  },
  {
    name: 'William Grant & Sons',
    company: 'James Buchanan & Co. Ltd',
    percentCanadian: 0,
    notes: 'Scottish whisky with no Canadian involvement.',
    categoryId: 'whiskey',
    aliases: ['william grant & sons whiskey'],
    popularity: 65,
  },
  {
    name: 'Jameson',
    company: 'Pernod Ricard',
    percentCanadian: 0,
    notes: 'Irish whisky with no Canadian involvement.',
    categoryId: 'whiskey',
    aliases: ['jameson whiskey'],
    popularity: 60,
  },
  {
    name: 'Chivas Regal',
    company: 'Chivas Brothers',
    percentCanadian: 0,
    notes: 'Scottish whisky with no Canadian involvement.',
    categoryId: 'whiskey',
    aliases: ['chivas regal whiskey'],
    popularity: 55,
  },
  {
    name: 'Jack Daniels',
    company: 'Brown-Forman Corporation',
    percentCanadian: 0,
    notes: 'American whisky with no Canadian involvement.',
    categoryId: 'whiskey',
    aliases: ['jack daniels whiskey'],
    popularity: 50,
  },
  {
    name: 'Jim Beam',
    company: 'Beam Suntory',
    percentCanadian: 0,
    notes: 'American whisky with no Canadian involvement.',
    categoryId: 'whiskey',
    aliases: ['jim beam whiskey'],
    popularity: 45,
  },
]

export const whiskeyCategory = {
  name: 'Whiskey',
  description:
    'A beverage distilled from a fermented mash of cereal grain. Comes in various styles and types, including rye, bourbon, and single-malt.',
  aliases: ['spirits', 'bourbon', 'rye', 'single-malt'],
}
